# -- Github Repository (**REQUIRED**)
githubRepo: OWNER/REPOSITORY

# -- Runner Service Account Name
ghaRunnerServiceAccountName: gha-runner-sa

# -- Runner Replicas
ghaRunnerReplicas: 1

# Runner Name prefix
ghaRunnerName: k8s-gha-runner

# -- Runner Labels
ghaRunnerLabels: 
  - k8s-sbeliakou

# -- Node Selector Rules
nodeSelector:
  kubernetes.io/os: linux

# -- Tolerations for the Runner Pods
tolerations: []
  # - key: node-role.kubernetes.io/worker
  #   effect: NoSchedule

# -- Additional Tools to be installed in the Runner Pods
# @default -- `[script,script,...]`
setupAdditionalTools: []
  # - |
  #   curl -L "https://dl.k8s.io/release/v1.30.13/bin/linux/amd64/kubectl" -o /usr/tools/bin/kubectl
  #   chmod +x /usr/tools/bin/kubectl
  # - |
  #   curl -L "https://github.com/stedolan/jq/releases/download/jq-1.8.0/jq-linux64"  -o /usr/tools/bin/jq
  #   chmod +x /usr/tools/bin/jq

# -- Graceful Stop Timeout for the Runner Pods
ghaRunnerGracefulStopTimeout: 15

# -- Runner RBAC Rules (**TOO MUCH FOR PRODUCTION!**)
# @default -- `[.. revise for your cases ..]`
# Developed for running CSI e2e tests in the Kubernetes cluster.
ghaRunnerClusterRoleRules:
  # Manage jobs and cronjobs
  - apiGroups: ["batch"]
    resources: 
      - "jobs"
      - "cronjobs"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Manage clusterroles and bindings
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "clusterroles"
      - "clusterrolebindings"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Additional resources required by test runner
  # (namespaces, service accounts, configmaps, secrets, events, nodes, pods, etc.)
  - apiGroups: [""]
    resources:
      - "namespaces"
      - "serviceaccounts"
      - "configmaps"
      - "secrets"
      - "events"
      - "nodes"
      - "nodes/proxy"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "pods"
      - "pods/ephemeralcontainers"
      - "pods/attach"
      - "pods/binding"
      - "pods/eviction"
      - "pods/portforward"
      - "pods/proxy"
      - "pods/exec"
      - "pods/status"
      - "replicationcontrollers"
      - "replicationcontrollers/scale"
      - "replicationcontrollers/status"
      - "services"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Additional permissions for logging and monitoring
  - apiGroups: [""]
    resources: 
    - "pods/log"
    verbs: ["get", "list", "watch"]
  
  # Manage deployments, daemonsets, replicasets, and statefulsets
  - apiGroups: ["apps"]
    resources:
      - "daemonsets"
      - "replicasets"
      - "statefulsets"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Manage storage classes
  - apiGroups: ["storage.k8s.io"]
    resources:
      - "storageclasses"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]