# -- Github Repository (**REQUIRED**)
githubRepo: OWNER/REPOSITORY

# -- Runner Service Account Name
ghaRunnerServiceAccountName: gha-runner-sa

# -- Runner Replicas
ghaRunnerReplicas: 1

# Runner Name prefix
ghaRunnerName: k8s-gha-runner

# -- Runner Labels
ghaRunnerLabels: 
  - k8s-sbeliakou

# -- Node Selector Rules
nodeSelector:
  kubernetes.io/os: linux

# -- Tolerations for the Runner Pods
tolerations: []
  # - key: node-role.kubernetes.io/worker
  #   effect: NoSchedule

# -- Additional Tools to be installed in the Runner Pods
# @default -- `[script,script,...]`
setupAdditionalTools:
  - |
    curl -L "https://dl.k8s.io/release/v1.30.13/bin/linux/amd64/kubectl" -o /usr/tools/bin/kubectl
    chmod +x /usr/tools/bin/kubectl
  - |
    curl -L "https://github.com/stedolan/jq/releases/download/jq-1.8.0/jq-linux64"  -o /usr/tools/bin/jq
    chmod +x /usr/tools/bin/jq

# -- Graceful Stop Timeout for the Runner Pods
ghaRunnerGracefulStopTimeout: 15

# -- Runner RBAC Rules (**TOO MUCH FOR PRODUCTION!**)
# @default -- `[.. revise for your cases ..]`
ghaRunnerClusterRoleRules:
  # Manage cronjobs in all namespaces
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Manage service accounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Manage configmaps
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Manage namespaces (careful: this is very powerful)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # ClusterRole and ClusterRoleBinding management
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Manage pods, nodes, events, persistent volumes and claims
  - apiGroups: [""]
    resources: ["events", "nodes", "nodes/proxy", "persistentvolumeclaims", "persistentvolumes", "pods/exec", "replicationcontrollers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Manage deployments, daemonsets, replicasets, and statefulsets
  - apiGroups: ["apps"]
    resources: ["daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Manage storageclasses
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  # Manage Services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]