# -- Github Repository
githubRepo: ORGANIZATION/REPOSITORY

# -- Runner Service Account Name
ghaRunnerServiceAccountName: gha-runner-sa

# -- Runner Replicas
ghaRunnerReplicas: 1

# Runner Name prefix
ghaRunnerName: k8s-gha-runner

# -- Runner Labels
ghaRunnerLabels: 
  - k8s-sbeliakou

# -- Node Selector Rules
nodeSelector:
  kubernetes.io/os: linux

# -- Tolerations for the Runner Pods
tolerations: {}
  # - key: node-role.kubernetes.io/worker
  #   effect: NoSchedule

# -- Additional Tools to be installed in the Runner Pods
# @default -- `[script,script,...]`
setupAdditionalTools:
  - |
    curl -L "https://dl.k8s.io/release/v1.30.13/bin/linux/amd64/kubectl" -o /usr/tools/bin/kubectl
    chmod +x /usr/tools/bin/kubectl
  - |
    curl -L "https://github.com/stedolan/jq/releases/download/jq-1.8.0/jq-linux64"  -o /usr/tools/bin/jq
    chmod +x /usr/tools/bin/jq

# -- Graceful Stop Timeout for the Runner Pods
ghaRunnerGracefulStopTimeout: 15