apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.ghaRunnerServiceAccountName }}-clusterrole
rules:
{{- range .Values.ghaRunnerClusterRoleRules }}
  - apiGroups: {{ toYaml .apiGroups | nindent 4 }}
    resources: {{ toYaml .resources | nindent 4 }}
    verbs: {{ toYaml .verbs | nindent 4 }}
{{- end }}